import type { ReactNode } from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Brand } from '@/constants/theme';

const LAST_UPDATED = '10 June 2026';

export default function TermsOfServiceScreen() {
  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={20} color={Brand.navy} />
          <Text style={styles.backText}>Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={{ width: 60 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <Text style={styles.updated}>Last updated: {LAST_UPDATED}</Text>

        <Section title="Agreement to Terms">
          By downloading or using TradeQuoteAI, you agree to be bound by these Terms of Service. If you do not agree, do not use the app. These terms apply to all users of the service.
        </Section>

        <Section title="About the Service">
          TradeQuoteAI is operated by KaasTech Ltd, a company registered in England and Wales. The app provides AI-assisted quote generation tools for painting and decorating tradespeople. The service is intended for professional business use.
        </Section>

        <Section title="User Accounts">
          You must create an account to use TradeQuoteAI. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. You must provide accurate information when registering. You must be at least 18 years old to use the service.
        </Section>

        <Section title="Acceptable Use">
          You agree to use TradeQuoteAI only for lawful purposes and in accordance with these Terms. You must not:{'\n\n'}
          • Attempt to gain unauthorised access to any part of the service.{'\n'}
          • Use the service to generate quotes for fraudulent or deceptive purposes.{'\n'}
          • Reverse engineer, decompile, or disassemble any part of the app.{'\n'}
          • Share your account credentials with third parties.{'\n'}
          • Use automated means to access the service in excessive volumes.
        </Section>

        <Section title="Subscription and Billing">
          TradeQuoteAI offers a free tier and paid subscription plans (Pro and Team). Paid subscriptions are billed monthly through Stripe. You may cancel your subscription at any time through the app's Settings screen. Cancellation takes effect at the end of the current billing period. Refunds are not provided for partial billing periods except where required by applicable law.
        </Section>

        <Section title="AI-Generated Content">
          Quote figures and line items generated by the AI are estimates only. TradeQuoteAI does not guarantee the accuracy of AI-generated quotes. You are solely responsible for reviewing all quotes before presenting them to customers. KaasTech Ltd accepts no liability for any financial loss arising from reliance on AI-generated content.
        </Section>

        <Section title="Intellectual Property">
          The TradeQuoteAI app, its design, and underlying technology are owned by KaasTech Ltd and protected by copyright and other intellectual property laws. You retain ownership of the quote content and business data you enter into the app.
        </Section>

        <Section title="Limitation of Liability">
          To the fullest extent permitted by law, KaasTech Ltd shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability to you shall not exceed the amount you paid to us in the 12 months preceding the claim.
        </Section>

        <Section title="Service Availability">
          We aim to provide a reliable service but do not guarantee uninterrupted access. The service may be temporarily unavailable for maintenance, updates, or reasons outside our control. We will endeavour to give advance notice of planned downtime where possible.
        </Section>

        <Section title="Termination">
          We reserve the right to suspend or terminate your account if you breach these Terms. You may delete your account at any time by contacting kenula@kaastech.co.uk. Upon termination, your data will be deleted within 30 days.
        </Section>

        <Section title="Governing Law">
          These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
        </Section>

        <Section title="Changes to These Terms">
          We may update these Terms from time to time. Significant changes will be notified via an in-app message. Continued use of the app after changes constitutes acceptance of the revised Terms.
        </Section>

        <Section title="Contact">
          KaasTech Ltd{'\n'}
          Email: kenula@kaastech.co.uk{'\n'}
          Website: kaastech.co.uk
        </Section>

        <View style={{ height: 32 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.sectionBody}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Brand.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Brand.white,
    borderBottomWidth: 1,
    borderBottomColor: Brand.border,
  },
  backBtn: { flexDirection: 'row', alignItems: 'center', width: 60 },
  backText: { fontSize: 13, color: Brand.orange, fontWeight: '500' },
  headerTitle: { fontSize: 16, fontWeight: '700', color: Brand.navy },
  content: { padding: 16, gap: 0 },
  updated: { fontSize: 11, color: Brand.textMuted, marginBottom: 16, textAlign: 'center' },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: Brand.navy, marginBottom: 8 },
  sectionBody: { fontSize: 13, color: Brand.textSecondary, lineHeight: 20 },
});
